### ISSUE TITLE
Can't connect controller after ROM has been loaded

### ISSUE THREAD

**Issue by VacationSoftware** [simple64/simple64#207]
**Describe the bug**
Controller doesn't work if connected after you load a ROM

**To Reproduce**
1. Disconnect controller (if connected)
2. Start emulator
3. Start ROM
3. Connect controller
4. Emulator will not recognize input

**Expected behavior**
Input to be recognized if controller is connected after ROM is started

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: Nvidia GeForce RTX 2070 Super

**Comment by mistrk7** [comment]
Confirmed and still present in latest build of March 14 2022, would really like to see a fix to this

**Comment by DarthSidious666** [comment]
Is this issue still happening on the latest build?

**Comment by DarthSidious666** [comment]
I can reproduce this in the current build, I think this would need an input device reset check or something.

**Comment by loganmc10** [comment]
I'm going to close this as fixed in https://github.com/simple64/simple64/releases/tag/v2023.04.12

You still can't connect a new controller after the game starts, and I'm OK with that. But what is fixed is that now you can disconnect/reconnect a controller during gameplay. Previously, if your controller disconnected during play, you'd have to restart the game
