### ISSUE TITLE
WCW Nitro freezing

### ISSUE THREAD

**Issue by Petersilientroll** [simple64/simple64#281]
Tested with v2022.08.5,

black screen:

NFL Quarterback Club 2000 (NTSC & PAL)
NFL Quarterback Club 2001
The Powerpuff Girls - Chemical X-Traction 

emulation stops:

NFL Quarterback Club 1999 (NTSC & PAL)

emulator crashes (I have to close it via task manager):

WCW Nitro

Windows 10, Intel CPU, NVidia GPU

**Comment by loganmc10** [comment]
Thanks, this is really good information.

I'm just putting notes here for myself:
All 3 NFL Quarterback Club games work with the Pure Interpreter, so something is wrong with the Cached Interpreter

**Comment by Petersilientroll** [comment]
If this helps: I had also black screens in NFL Quarterback Club 1998 and Xena -  The Talisman of Fate. Both games work since v2022.08.1.

**Comment by loganmc10** [comment]
Thanks, I found a fix for the 3 NFL Quarterback Club games and Powerpuff Girls, they'll be fixed in the next release.

The issue with WCW Nitro is sort of the same with NFL Quarterback Club 1998 and Xena, they'll are quite particular when it comes to timing. I still don't have the timing perfect, so these games sort of go in and out of compatibility as the timing is modified. Hopefully, over time this emulator will be able to converge on more accurate timing emulation, which will make all those games more stable.

For now though, I'll probably just leave WCW Nitro as-is. I think any attempt I make to modify timing numbers to make it work will probably just break other games.
