### ISSUE TITLE
netplay desync in mario party 3

### ISSUE THREAD

**Issue by Dolphin2Point1** [simple64/simple64#358]
**Describe the bug**
Players see the game anywhere from 2-20 seconds later. Some players have very little display lag, and some have tens of seconds of it. The inputs are received by me, the host, at about the same time that they have been pressed. The framerate of everyone's game is unaffected.

**To Reproduce**
1. Open a netplay game of mario party 3
2. on the character select screen, you can see that there is a massive amount of display delay for some players

**Expected behavior**

**Screenshots**
I did not manage to get a video of the problem. I will try to get one soon.

**Desktop (please complete the following information):**
 - OS: three players using windows, one (me, the host of the netplay game) using linux.
 - Version: Windows 10/11 is used by the other players, and I'm using arch linux (flatpak build of simple64) 
 - GPU: I'm using a radeon 5500xt, not sure about other players (but it shouldn't matter.)

**Comment by loganmc10** [comment]
A true desync (meaning the outcome of the game is different for each player) will cause a message/pop up to appear notifying you that the games have desynced.

The players that are experiencing delayed input are seeing that because of local performance issues. They can try to set upscaling to 1 if they've turned on upscaling.

If someone's game can't play at full speed (meaning 60FPS), they are going to experience input lag, since they are viewing the game "behind" everyone else. Simple64's netplay implementation will use fast forward to allow people to catch up if they are behind, but if their computer can't fast forward the game (can't run it at 60 FPS or higher), they'll never catch up. So the GPU of each player does matter in this case.

Some other emulator netplay implementations ensure that everyone stays in perfect sync, meaning that it will freeze the game for everyone in case someone falls behind. Simple64 doesn't do this, it treats each player's experience independently, so if a player falls behind (because of a poor internet connection or a slow PC), it doesn't affect the experience of the others.

**Comment by Dolphin2Point1** [comment]
does the speed limiter have any affect on the framerate for individual players?

**Comment by loganmc10** [comment]
I'm not sure what you meant exactly. Manually fast forwarding/disabling the speed limiter doesn't work during netplay.

During netplay, the game will run at 60FPS, if netplay detects that you are running behind the other players, it will temporarily fast forward your game (by disabling the speed limiter) until you are caught up.

If it's not able to fast forward your game, you'll be perpetually behind, which manifests itself as input lag.

**Comment by Dolphin2Point1** [comment]
does vsync or any other form of adaptive sync keep the emulator from catching back up?

**Comment by loganmc10** [comment]
Yes it would, the emulator force disables the vsync option during netplay[1], but if there was some OS level vsync happening, it could prevent fast forwarding (depending on the refresh rate of the monitor). A person could test this by ensuring that fast forward works in single player (by pressing Y to disable the speed limiter).

[1]https://github.com/simple64/simple64/blob/55c8c7d6a1dd6ee82f50f537dfb89c314f759af3/parallel-rdp-standalone/gfx_simple64.c#L267

**Comment by Dolphin2Point1** [comment]
so turns out it is a graphics driver issue. one of my friends has intel xe graphics on windows 11, and needs to change his graphics settings. once i'm done fixing this issue i will send back a response on how to fix this, and i suggest you add this somewhere on your netplay guide.

**Comment by Dolphin2Point1** [comment]
for intel xe
1. open intel graphics command center
2. in the home tab, click manually select. if there's nothing about games on the home tab, update your drivers and come back once they've been updated.
3. select simple64 as the game file
4. once you have added simple64, select it from the games menu
5. create a custom profile for the game
6. make sure to disable vsync in this new profile

I still need to figure out how to do it on amd adrenalin edition, as another one of my friends is using a radeon gpu

**Comment by Dolphin2Point1** [comment]
turns out, intel graphics command center doesnt do this anymore, and now you need to use intel arc control. why? i dont know but fixing graphics settings is going to make me go insane.

**Comment by DarthSidious666** [comment]
Radeon is really simple.
Open up Adrenalin and click Gaming, if the game's not there click the three verticcal dots and then Add A Game.

Scroll down to Simple64-gui and click it then you can set the options for that game\application.
