### ISSUE TITLE
Error when opening

### ISSUE THREAD

**Issue by ExGuestCJ** [simple64/simple64#369]
**Describe the bug**
"The procedure entry point SystemParametersInfoForDpi could not be located in the dynamic link library
C:/Users/*insert username here*/Downloads/Juegos/Roms/n64/simple64-win64-6a5db81/simple64/Qt6Gui.dll."

**To Reproduce**
Open simple64-gui.exe

**Expected behavior**
The emulator running fine

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 8.1
 - GPU: idk

**Comment by loganmc10** [comment]
Windows 8.1 is not a supported OS

**Comment by ExGuestCJ** [comment]
damn

**Comment by loganmc10** [comment]
It is because Qt6, the programming framework that is used by Simple64, doesn't support Windows 7 or 8[1]

"Both Windows 7 or 8.x version support will not be available for Qt 6. Microsoft discontinued the support for both Windows versions some time ago, and as a vendor, we can no longer maintain support for these windows versions in Qt 6."

[1]https://www.qt.io/blog/qt6-development-hosts-and-targets
