### ISSUE TITLE
Playing for a few seconds will make games freeze visually flickering between two frames

### ISSUE THREAD

**Issue by RadFox34** [simple64/simple64#434]
https://i.imgur.com/umsr4nF.gif
Hope this link works

 - OS: Windows
 - Version: 10
 - GPU: Nvidia GeForce GTX 1060 3GB

**Comment by tomster785** [comment]
I also have this issue, I've done some testing and I've learned that this is most likely down to the parallel update a few builds ago, because the first build this issue occurs in is 981d2d4 (which is the first appearance of the recent parallel rdp update), and the last working version is the one right before it 0321396. Within about 10-20 seconds of gameplay the issue you are describing happens to me.

I thought that maybe an update to the parallel rdp might mean that maybe its just using new vulkan extensions or something, so I made sure to update my graphics drivers, restart, troubleshoot my computer, etc. I couldn't find any issues elsewhere, the only thing that I can find that narrows down the issue is that the issues start with 981d2d4, which makes me think my computer is not the issue, and the fact that you're also experiencing this makes me think that too. I have a GTX 1080 btw, so we have the same generation of graphics card, so it might just be that our gpus are getting too old and parallel no longer supports our cards, I hope that's not it.

**Comment by Pat86** [comment]
Same Problem here. GTX 1070.

**Comment by TomaSajt** [comment]
Same issue here, but on Linux.

I don't actually encounter this issue with https://github.com/simple64/simple64/commit/981d2d459b764a8622adc8bef66a28da74f47c54.
I only encounter it after https://github.com/simple64/simple64/commit/cf08f49a2162f2b46de88f1df6f0212266604771 (<-- this doesn't build, so use the next commit instead: https://github.com/simple64/simple64/commit/4af7a319c334e8b8eda2fcc152d10808251179ab)

**Comment by threenator** [comment]
I'm having exactly the same issue, Windows 10, GTX 980.

**Comment by lmcgregoruk** [comment]
I'm having the same issue, Windows 10, GTX 1060 6GB.
Although it can happen anytime from just starting a game, to seconds or even minutes after starting.

**Comment by Myfharad** [comment]
Same issue as of latest release. GTX 1070

**Comment by TomatoLoli** [comment]
Can confirm same issue in c96e168 is occurring for myself in Pokemon Stadium 2 (Europe) after about 5 mins.
When I rollback to the version suggested by @tomster785 it works fine. 0321396

Windows 11 Pro 64-bit (10.0, Build 22631)
Intel(R) Core(TM) i7-8700K CPU
NVIDIA GeForce GTX 1080 Ti (Driver Version: 560.94)
